version: "3.8"

services:

  backend:
    build: .
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 프로젝트명.wsgi:application"
    ports:
      - 8000:8000
    working_dir: /srv/docker-server/
    volumes:
      - ./:/srv/docker-server/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:14.4-alpine
    container_name: postgresql_service
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${SQL_DATABASE}"
      POSTGRES_USER: "${SQL_USER}"
      POSTGRES_PASSWORD: "${SQL_PASSWORD}"
    ports:
      - "5432:5432"
